### ISSUE TITLE
BUG: Cursor Positioning Issue in React 18 when using setCustomNativeDragPreview

### ISSUE THREAD

**Issue by kushanksriraj** [atlassian/pragmatic-drag-and-drop#96]
When I use react 18's creatRoot API, and using `setCustomNativeDragPreview` to show the dragging preview, the cursor position where I picked the card always goes to top left, but it works fine with the react 17's `render` API.

Please check the below video and attached sandbox link.

[Stackblitz](https://stackblitz.com/~/github.com/kushanksriraj/pragmatic-dnd?file=src/main.tsx)

https://github.com/user-attachments/assets/d586aa36-a2d8-459b-af19-cbda7e3330e1

**Comment by kushanksriraj** [comment]
Looks like there is already similar issue: https://github.com/atlassian/pragmatic-drag-and-drop/issues/54

**Comment by alexreardon** [comment]
Hi there,

This react@18 issue was resolved in `1.1.6`

https://atlassian.design/components/pragmatic-drag-and-drop/core-package/changelog/changelog#116

Could you please try upgrading and then trying again? Cheers

**Comment by kushanksriraj** [comment]
I tried upgrading to 1.2.1 but unfortunately it is still not working: https://stackblitz.com/~/github.com/kushanksriraj/pragmatic-dnd?file=src/main.tsx
```
"@atlaskit/pragmatic-drag-and-drop": "1.2.1",
```

Thank you for the great work, really appreciate it!

**Comment by alexreardon** [comment]
Thank you. Bug confirmed. I now have a work in progress fix for `react@18`

**Comment by alexreardon** [comment]
A fix has been shipped for this bug in `1.2.3`. Thanks for helping to provide the information required to get this actioned quickly @kushanksriraj.

Enjoy!
